spring:
  application:
    name: "configserver"
  profiles:
#    active: native   this is for classpath properties
    active: git
  cloud:
    config:
      server:
#        native:
#          search-location: "classpath:/config"
        git:
          uri: "https://github.com/whojayantkumar/config-properties-ms.git"
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 200
          skip-ssl-validation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: "A3F2446B6472D59FB3E9B6C45126B"

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
server:
  port: 8071
